import script for iconLibrary
kptdobe/franklin-acom-import pull request #16
Opened 2023-03-28 08:46 UTC by pulkitSoni526

import script for iconLibrary

2023-03-28 08:54 UTC, aishwaryamathuria commented on tools/importer/data.json
Please remove the data file from import script

2023-03-28 08:55 UTC, aishwaryamathuria requested changes

2023-03-28 08:55 UTC, aishwaryamathuria commented on tools/importer/data.json
Please remove the data file from import script

2023-03-28 08:59 UTC, Deva309 requested changes

2023-03-28 08:59 UTC, Deva309 commented on tools/importer/import.js
> +
Remove these extra spaces added.
Not needed and format the code before raising the PR.

2023-03-28 08:59 UTC, Deva309 commented on tools/importer/import.js
> +
Same here

2023-03-28 08:59 UTC, Deva309 commented on tools/importer/import.js
> +
same here

2023-03-28 08:59 UTC, Deva309 commented on tools/importer/import.js
> +          case constants.gradientLine:
Could you please format the code correctly?
Also, run eslint as well.

2023-03-28 08:59 UTC, Deva309 commented on tools/importer/import.js
> +          // defaulticonblock
why defaulticonblock?

2023-03-28 08:59 UTC, Deva309 commented on tools/importer/rules/iconLibrary.js
> +export default function iconLibrary(block, document) {
Format this file and run eslint as well

2023-03-28 08:59 UTC, Deva309 commented on tools/importer/services/getBlocks.js
> +    // const jsonPath = ['https://aishwaryamathuria.github.io/franklin-cc-json/cc', relativePath.join('/'), 'info.json'].join('/');
Remove these changes if you have used it at your local only

2023-03-29 08:20 UTC, Deva309 approved these changes

2023-03-29 08:20 UTC, merged